baseURL = "https://JiniEun.github.io/"
title = "Jin"
theme = "hugo-coder"
languageCode = "ko"
defaultContentLanguage = "ko"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "JiniEun/blog-comments"
# disableComments = true

[module]
[module.hugoVersion]
min = "0.77.0"

[params]
author = "은진"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Jin's personal website"
keywords = "blog,developer,personal"
info = ["Backend Developer", "Java Developer"]
avatarURL = "images/avatar.jpg"
# favicon_32 = "/img/favicon-32x32.png"
# favicon_16 = "/img/favicon-16x16.png"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
commit = "https://github.com/JiniEun/blog"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[params.utterances]
repo = "JiniEun/blog-comments" # https://utteranc.es/#heading-repository

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'", 
  "'unsafe-inline'", 
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/jinieun/"

#[[params.social]]
#name = "Gitlab"
#icon = "fa fa-2x fa-gitlab"
#weight = 2
#url = "https://gitlab.com/johndoe/"

#[[params.social]]
#name = "Twitter"
#icon = "fa fa-2x fa-twitter"
#weight = 3
#url = "https://twitter.com/johndoe/"

#[[params.social]]
#name = "LinkedIn"
#icon = "fa fa-2x fa-linkedin"
#weight = 4
#url = "https://www.linkedin.com/in/johndoe/"

#[[params.social]]
#name = "Medium"
#icon = "fa fa-2x fa-medium"
#weight = 5
#url = "https://medium.com/@johndoe"

[[params.social]]
name = "Blog"
icon = "fa fa-2x fa-tag"
weight = 5
url = "https://jules-jc.tistory.com/"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://jinieun.github.io/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

# [languages.en]
# languageName = ":us:"

# [languages.en.params]
# author = "Eun Jin"
# info = ["Backend Developer", "Java Developer"]
# description = "Jin's personal website"
# keywords = "blog,developer,pessoal"

# [[languages.en.menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

# [[languages.en.menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"

[languages.ko]
languageName = ":ko:"

# [languages.ko.params]
# author = "김은진"
# info = ["웹 백엔드 개발자"]
# description = "백엔드 개발자"
# keywords = "blog,developer,pessoal"

[[languages.ko.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.ko.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.ko.menu.main]]
name = "Projets"
weight = 3
url = "projects/"

[[languages.ko.menu.main]]
name = "Contact"
weight = 5
url = "contact/"